name: Automate CSV Integration

on:
  workflow_dispatch: # For manual triggering during testing
  push:
    paths:
      - "datahub/*.csv" # Trigger only for changes in CSV files in the datahub folder
  pull_request:
    paths:
      - "datahub/*.csv"

permissions:
  contents: write # Required for committing and pushing changes

jobs:
  monitor_changes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Filter CSV changes
        uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            csv-files:
              - 'datahub/*.csv' # Monitor all CSV files in the datahub folder

  integrate_data:
    runs-on: ubuntu-latest
    needs: monitor_changes
    if: ${{ needs.monitor_changes.outputs.csv-files == 'true' }} # Run only if CSV files are changed

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Combine CSV Files
        run: |
          echo "Changes detected in datahub folder. Starting CSV integration..."
          chmod +x integrate_data.sh
          ./integrate_data.sh

      - name: Notify CSV Integration Success
        run: echo "CSV files have been successfully integrated."

      - name: Upload Combined CSV as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: combined_csv
          path: db_folder/combined.csv

      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "CodeWithSophia"
          git config --global user.email "ezeahibuchukwu@gmail.com"
          git add db_folder/combined.csv
          git commit -m "Data Integration Script"
          git push
