name: Automate CSV Integration

on:
  workflow_dispatch: # Use this when you are still testing the linter 
  push:
    paths:
      - "datahub/*.csv" # Trigger only for changes in CSV files in the datahub folder
  pull_request:
    paths:
      - "datahub/*.csv"
  permissions:
    contents: write


jobs:
  monitor_changes:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Filter CSV changes
      uses: dorny/paths-filter@v3
      id: changes
      with:
        filters: |
          csv-files:
            - 'datahub/*.csv' # Monitor all CSV files in the datahub folder

  integrate_data:
    runs-on: ubuntu-latest
    needs: monitor_changes
    steps:
      - name: checkout repository
        uses: actions.checkout@v3
      - name: Combine CSV Files
      if: steps.changes.outputs.csv-files == 'true'
      run: |
        echo "Changes detected in datahub folder. Starting CSV integration..."
      - name: Make script executable
        run: chmod +x integrate_data.sh
      - name: run the script
        run: ./integrate_data.sh

      - name: Notify CSV Integration Success
        if: steps.changes.outputs.csv-files == 'true'
        run: echo "CSV files have been successfully integrated."

      - name: Upload Combined CSV as Artifact
        if: steps.changes.outputs.csv-files == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: combined_csv
          path: db_folder/combined.csv
      - name: commit changes
        run: |
          git config--global user.name "CodeWithSophia"
          git config--global user.email "ezeahibuchukwu@gmail.com"
          git add db_folder/combined.csv
          git commit -m "Data Integration Script"

      - name: push the changes
        env: 
          GITHUB_TOKEN:${{ secrets.GITHUB_TOKEN }}
        run: git push
